config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords" }

  root 'admin/usuarios#index'

  namespace :admin do
    resources :usuarios
    resources :grupos
    resources :categories
    resources :customers
    resources :employees
    resources :work_types
    resources :tickets
    resources :imports, only: [:index]

    post 'usuarios/delete/:id' => 'usuarios#destroy'
    post 'grupos/delete/:id' => 'grupos#destroy'
    post 'categories/delete/:id' => 'categories#destroy'
    post 'customers/delete/:id' => 'customers#destroy'
    post 'employees/delete/:id' => 'employees#destroy'
    post 'work_types/delete/:id' => 'work_types#destroy'
    post 'tickets/delete/:id' => 'tickets#destroy'

  end

end

app/controllers/admin/usuarios_controller.rb
class Admin::UsuariosController < ApplicationController

    load_and_authorize_resource :class => User

    # GET /high_scores
    # GET /high_scores.json
    def index
        @users = User.all
    end

    # GET /high_scores/1
    # GET /high_scores/1.json
    def show
    end

    # GET /high_scores/new
    def new
        @user = User.new
    end

    # GET /high_scores/1/edit
    def edit
        @resource = User.find(params[:id])
    end

    def destroy
        @user = User.find(params[:id])
        respond_to do |format|
            if @user.destroy
                flash[:estado] = "Excluído-sucesso"
                format.html { redirect_to action: 'index' }
                format.json { head :no_content }
            end
        end
    end

end

app/helpers/admin/usuarios_helper.rb
module Admin::UsuariosHelper
end

app/views/admin/usuarios/_form.html.erb
<% content_for :style do -%>
    <%= stylesheet_link_tag "admin/select2" %> <!-- dropdown -->
  <%= stylesheet_link_tag 'admin/jquery-ui-1.10.4.custom' %>
<% end -%>

<% content_for :script do -%>
    <%= javascript_include_tag "admin/select2" %> <!-- dropdown -->
    <%= javascript_include_tag "admin/select2_locale_pt-BR" %> <!-- dropdown -->
	<%= javascript_include_tag 'jquery.validate.min' %>

    <script>
        //Validação do formulário
        $("form.formValidate").validate({
            rules: {
                'user[nome]':
                {
                    required: true
                },
                'user[email]':
                {
                    required: true,
                    email: true
                }
            },
            messages: {
                'user[nome]': {
                    required: "O nome do usuário é obrigatório."
                },
                'user[email]': {
                    required: "O e-mail é obrigatório.",
                    email: "Insira um e-mail válido"
                }
            }
        });
    </script>

<% end -%>

<div class="panel-body">
    <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "form-horizontal formValidate"}) do |f| %>
      <%= f.hidden_field :id %>
	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Nome
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :nome, :required => true, :autofocus => true, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">E-mail
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :email, :required => true, :class => "form-control" %>
	  		</div>
	  	</div>

      <div class="form-group">
        <label class="control-label col-lg-2">Status
        </label>
        <div class="col-lg-4 iconic-input right">
          <%= f.select(:ativo, [['Ativo', 1],
          ['Inativo', 0]], {}, { :class => 'form-control', :style => 'float: left; max-width: 85%;' } )%>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-lg-2">Tipo de Usuário
        </label>
        <div class="col-lg-4 iconic-input right">
          <%= f.select(:roles_mask, [['Admin', 1],
                                    ['Funcionário', 2],
                                    ['Cliente', 4]],
                                    {}, { :class => 'form-control', :style => 'float: left; max-width: 85%;' } )%>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-lg-2">Nova Senha
        </label>
        <div class="col-lg-4 iconic-input right">
          <%= f.password_field :password, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <label class="control-label col-lg-2">Confirmação de Senha
        </label>
        <div class="col-lg-4 iconic-input right">
          <%= f.password_field :password_confirmation, :class => "form-control" %>
        </div>
      </div>

		<%= link_to 'Voltar', {:action => "index"}, :class => 'btn btn-shadow btn-default' %>
		<div class="pull-right">
			<%= f.submit "Salvar", class: "btn btn-shadow btn-primary" %>
		</div>
	<% end %>

</div>

 <span class="loader">
 <%= image_tag "admin/loading.gif", :width => "80px" %>
</span>
<div style="position:fixed;" class="maskLoader"></div>

app/views/admin/usuarios/_grid.html.erb
<%# <td class="center hidden-phone">5</td> - classe para centralizar e esconder qdo responsivo %>

<table  class="display table table-bordered table-striped" id="data_table">
    <thead>
    <tr>
        <th>Nome</th>
        <th class="hidden-phone">E-mail</th>
        <th class="hidden-phone">Status</th>
        <% if can? :update, User %>
            <th>Editar</th>
        <% end %>
        <% if can? :destroy, User %>
            <th>Excluir</th>
        <% end %>
    </tr>
    </thead>
    <tbody>

    <% @users.each do |user| %>
        <tr>
            <td><%= user.nome %></td>
            <td class="hidden-phone"><%= user.email %></td>
            <td class="hidden-phone">
              <% if user.ativo %>
                Ativo
              <% else %>
                Inativo
              <% end %>
            </td>
            <% if can? :update, User %>
                <td class="center">
                    <%= link_to(edit_admin_usuario_path(user), :class => 'btn btn-primary btn-xs') do %>
                        <i class="fa fa-pencil fa-lg"></i>
                    <% end %>
                </td>
            <% end %>
            <% if can? :destroy, User %>
                <td class="center">
                    <%= link_to(admin_usuario_path(user), :class => 'btn btn-danger btn-xs btn-excluir-grid', :id => user.id) do %>
                        <i class="fa fa-trash-o fa-lg"></i>
                    <% end %>
                </td>
            <% end %>
        </tr>
    <% end %>

    </tbody>

</table>

<span class="loader" style="left:50%;">
    <%= image_tag "admin/loading.gif", :width => "80px" %>
</span>
<div style="position:fixed;" class="maskLoader"></div>

<script type="text/javascript">
    $(function (){
        //datatable
        $('#data_table').dataTable( {
            "aaSorting": [[ 0, "asc" ]],
            "oLanguage": {
                "sUrl": "/datatable_pt.txt"
            },
            "aoColumnDefs": [
                { "bSortable": true, "aTargets": [ 0 ] },
                { "bSearchable": false, "aTargets": [ 2, 3 ] }
            ]
        } );
    });
</script>

app/views/admin/usuarios/edit.html.erb
<section class="panel">
	<header class="panel-heading">
		Edição de usuário
	</header>

	<div id="renderForm">
		<%= render 'form' %>
	</div>
</section>

app/views/admin/usuarios/index.html.erb
<% content_for :style do -%>
    <%= stylesheet_link_tag "admin/demo_page" %> <!-- datatable -->
    <%= stylesheet_link_tag "admin/demo_table" %> <!-- datatable -->
    <%= stylesheet_link_tag "admin/DT_bootstrap" %> <!-- datatable -->
<% end -%>

<% content_for :script do -%>
    <%= javascript_include_tag 'admin/jquery.dataTables' %> <!-- datatable -->
    <%= javascript_include_tag "admin/DT_bootstrap" %> <!-- datatable -->

    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {

            $(document).on('click','a.btn-excluir-grid',function () {
                if(confirm("Você tem certeza que deseja excluir?"))
                {
                    $('span.loader').show();
                    $('div.maskLoader').show();
                    var linha = $(this).closest('tr');
                    id = $(this).attr('id');
                    $.ajax({
                        url: '/admin/usuarios/delete/'+id,
                        type: 'POST',
                        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                        // data: {id: id},
                    })
                    .done(function() {
                        // $(linha).remove();
                        $.get(this.href, $(this).serialize(), null, 'script');
                    })
                    .fail(function() {
                        console.log("erro ao excluir usuário");
                        $('span.loader').hide();
                        $('div.maskLoader').hide();
                    });
                    $.ajaxSetup({
                      headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                      }
                    });
                }
                return false;
            });

        } );
    </script>

<% end -%>

<section class="panel">
    <header class="panel-heading">
        Lista de Usuários
    </header>
    <%= if flash[:estado] == "Inserido-sucesso"
        raw('<div class="alert alert-success fade in fadeOut">
                <button class="close close-sm" type="button" data-dismiss="alert">
                    <i class="fa fa-times"></i>
                </button>
                <strong>Usuário</strong> incluído com sucesso.
            </div>')
        elsif flash[:estado] == "Atualizado-sucesso"
        raw('<div class="alert alert-success fade in fadeOut">
                <button class="close close-sm" type="button" data-dismiss="alert">
                    <i class="fa fa-times"></i>
                </button>
                <strong>Usuário</strong> atualizado com sucesso.
            </div>')
        elsif flash[:estado] == "Excluído-sucesso"
        raw('<div class="alert alert-success fade in fadeOut">
                <button class="close close-sm" type="button" data-dismiss="alert">
                    <i class="fa fa-times"></i>
                </button>
                <strong>Usuário</strong> excluído com sucesso.
            </div>')
    end %>
    <div class="panel-body">
        <div class="btn-group">
            <% if can? :create, User %>
                <%= link_to(new_admin_usuario_path, :class => 'btn btn-shadow btn-primary', :style => 'margin-bottom:10px;') do %>
                    Adicionar <i class="fa fa-plus"></i>
                <% end %>
            <% end %>
        </div>
        <div class="adv-table">
            <%= render 'grid' %>
        </div>
    </div>
</section>

app/views/admin/usuarios/new.html.erb
<section class="panel">
	<header class="panel-heading">
		Cadastro de usuário
	</header>

	<div id="renderForm">
		<%= render 'form' %>
	</div>
</section>