config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords" }

  root 'admin/usuarios#index'

  namespace :admin do
    resources :usuarios
    resources :grupos
    resources :categories
    resources :customers
    resources :employees
    resources :work_types
    resources :tickets
    resources :imports, only: [:index]

    post 'usuarios/delete/:id' => 'usuarios#destroy'
    post 'grupos/delete/:id' => 'grupos#destroy'
    post 'categories/delete/:id' => 'categories#destroy'
    post 'customers/delete/:id' => 'customers#destroy'
    post 'employees/delete/:id' => 'employees#destroy'
    post 'work_types/delete/:id' => 'work_types#destroy'
    post 'tickets/delete/:id' => 'tickets#destroy'

  end

end

app/models/admin/grupo.rb
class Admin::Grupo < ActiveRecord::Base

  has_many :admin_employees, :class_name => 'Admin::Employee'

  validates :nome, :presence => {:message => "Campo obrigatório"}
  validates :custo_total, :presence => {:message => "Campo obrigatório"}

end

app/controllers/admin/grupos_controller.rb
class Admin::GruposController < ApplicationController

  before_action :set_grupo, only: [:edit, :destroy]
  load_and_authorize_resource

  def index
    @grupos = Admin::Grupo.select('id, nome, custo_total').all
  end

  def new
    @grupo = Admin::Grupo.new
  end

  def edit
  end

  def create
    @grupo = Admin::Grupo.new(grupo_params)
    respond_with @grupo, location: @grupo.save ? admin_grupos_path : new_admin_grupo_path(@grupo)
  end

  def update
    respond_with @grupo, location: @grupo.update(grupo_params) ? admin_grupos_path : edit_admin_grupo_path(@grupo)
  end

  def destroy
    respond_with @grupo, location: admin_grupos_path if @grupo.destroy
  end

  private

    def set_grupo
      @grupo = Admin::Grupo.find(params[:id])
    end

    def grupo_params
      params.require(:admin_grupo).permit(:nome, :custo_total)
    end


end

app/helpers/admin/grupos_helper.rb
module Admin::GruposHelper
end

app/views/admin/grupos/_form.html.erb
<% content_for :style do -%>
    <%= stylesheet_link_tag "admin/select2" %> <!-- dropdown -->
  <%= stylesheet_link_tag 'admin/jquery-ui-1.10.4.custom' %>
<% end -%>

<% content_for :script do -%>
    <%= javascript_include_tag "admin/select2" %> <!-- dropdown -->
    <%= javascript_include_tag "admin/select2_locale_pt-BR" %> <!-- dropdown -->
	<%= javascript_include_tag 'jquery.validate.min' %>

    <script>
        //Validação do formulário
        $("form.formValidate").validate({
            rules: {
                'admin_grupo[nome]':
                {
                    required: true
                },
                'admin_grupo[custo_total]':
                {
                    required: true
                }
            },
            messages: {
                'admin_grupo[nome]': {
                    required: "O nome do grupo é obrigatório."
                },
                'admin_grupo[custo_total]': {
                    required: "O custo total do grupo é obrigatório."
                }
            }
        });
    </script>

<% end -%>

<div class="panel-body">
    <%= simple_form_for(@grupo, html: {class: "form-horizontal formValidate"}) do |f| %>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Nome
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :nome, :required => true, :autofocus => true, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Custo total do grupo
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :custo_total, :required => true, :class => "form-control" %>
	  		</div>
	  	</div>

		<%= link_to 'Voltar', {:action => "index"}, :class => 'btn btn-shadow btn-default' %>
		<div class="pull-right">
			<%= f.submit "Salvar", class: "btn btn-shadow btn-primary" %>
		</div>
	<% end %>

</div>

 <span class="loader">
 <%= image_tag "admin/loading.gif", :width => "80px" %>
</span>
<div style="position:fixed;" class="maskLoader"></div>

app/views/admin/grupos/_grid.html.erb
<%# <td class="center hidden-phone">5</td> - classe para centralizar e esconder qdo responsivo %>

<table  class="display table table-bordered table-striped" id="data_table">
    <thead>
    <tr>
        <th>Nome</th>
        <th class="hidden-phone">Custo Total</th>
        <% if can? :update, Admin::Grupo %>
            <th>Editar</th>
        <% end %>
        <% if can? :destroy, Admin::Grupo %>
            <th>Excluir</th>
        <% end %>
    </tr>
    </thead>
    <tbody>

    <% @grupos.each do |grupo| %>
        <tr>
            <td><%= grupo.nome %></td>
            <td class="hidden-phone"><%= grupo.custo_total %></td>
            <% if can? :update, Admin::Grupo %>
                <td class="center">
                    <%= link_to(edit_admin_grupo_path(grupo), :class => 'btn btn-primary btn-xs') do %>
                        <i class="fa fa-pencil fa-lg"></i>
                    <% end %>
                </td>
            <% end %>
            <% if can? :destroy, Admin::Grupo %>
                <td class="center">
                    <%= link_to(admin_grupo_path(grupo), :class => 'btn btn-danger btn-xs btn-excluir-grid', :id => grupo.id) do %>
                        <i class="fa fa-trash-o fa-lg"></i>
                    <% end %>
                </td>
            <% end %>
        </tr>
    <% end %>

    </tbody>

</table>

<span class="loader" style="left:50%;">
    <%= image_tag "admin/loading.gif", :width => "80px" %>
</span>
<div style="position:fixed;" class="maskLoader"></div>

<script type="text/javascript">
    $(function (){
        //datatable
        $('#data_table').dataTable( {
            "aaSorting": [[ 0, "asc" ]],
            "oLanguage": {
                "sUrl": "/datatable_pt.txt"
            },
            "aoColumnDefs": [
                { "bSortable": true, "aTargets": [ 0 ] },
                { "bSearchable": false, "aTargets": [ 2, 3 ] }
            ]
        } );
    });
</script>

app/views/admin/grupos/edit.html.erb
<section class="panel">
	<header class="panel-heading">
		Edição de Grupo
	</header>

	<div id="renderForm">
		<%= render 'form' %>
	</div>
</section>

app/views/admin/grupos/index.html.erb
<% content_for :style do -%>
    <%= stylesheet_link_tag "admin/demo_page" %> <!-- datatable -->
    <%= stylesheet_link_tag "admin/demo_table" %> <!-- datatable -->
    <%= stylesheet_link_tag "admin/DT_bootstrap" %> <!-- datatable -->
<% end -%>

<% content_for :script do -%>
    <%= javascript_include_tag 'admin/jquery.dataTables' %> <!-- datatable -->
    <%= javascript_include_tag "admin/DT_bootstrap" %> <!-- datatable -->

    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {

            $(document).on('click','a.btn-excluir-grid',function () {
                if(confirm("Você tem certeza que deseja excluir?"))
                {
                    $('span.loader').show();
                    $('div.maskLoader').show();
                    var linha = $(this).closest('tr');
                    id = $(this).attr('id');
                    $.ajax({
                        url: '/admin/grupos/delete/'+id,
                        type: 'POST',
                        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                        // data: {id: id},
                    })
                    .done(function() {
                        // $(linha).remove();
                        $.get(this.href, $(this).serialize(), null, 'script');
                    })
                    .fail(function() {
                        console.log("erro ao excluir");
                        $('span.loader').hide();
                        $('div.maskLoader').hide();
                    });
                    $.ajaxSetup({
                      headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                      }
                    });
                }
                return false;
            });

        } );
    </script>

<% end -%>

<section class="panel">
    <header class="panel-heading">
        Lista de Grupos
    </header>

  <% if flash[:notice] %>
      <div class="alert alert-success fade in fadeOut">
        <button class="close close-sm" type="button" data-dismiss="alert">
          <i class="fa fa-times"></i>
        </button>
        <%= flash[:notice] %>
      </div>
  <% end %>

    <div class="panel-body">
        <div class="btn-group">
            <% if can? :create, Admin::Grupo %>
                <%= link_to(new_admin_grupo_path, :class => 'btn btn-shadow btn-primary', :style => 'margin-bottom:10px;') do %>
                    Adicionar <i class="fa fa-plus"></i>
                <% end %>
            <% end %>
        </div>
        <div class="adv-table">
            <%= render 'grid' %>
        </div>
    </div>
</section>

app/views/admin/grupos/new.html.erb
<section class="panel">
	<header class="panel-heading">
		Cadastro de Grupo
	</header>

	<div id="renderForm">
		<%= render 'form' %>
	</div>
</section>