config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations", passwords: "passwords" }

  root 'admin/usuarios#index'

  namespace :admin do
    resources :usuarios
    resources :grupos
    resources :categories
    resources :customers
    resources :employees
    resources :work_types
    resources :tickets
    resources :imports, only: [:index]

    post 'usuarios/delete/:id' => 'usuarios#destroy'
    post 'grupos/delete/:id' => 'grupos#destroy'
    post 'categories/delete/:id' => 'categories#destroy'
    post 'customers/delete/:id' => 'customers#destroy'
    post 'employees/delete/:id' => 'employees#destroy'
    post 'work_types/delete/:id' => 'work_types#destroy'
    post 'tickets/delete/:id' => 'tickets#destroy'

  end

end

app/models/admin/customer.rb
class Admin::Customer < ActiveRecord::Base

    validates :name, :presence => {:message => "Campo obrigatório"}
    validates :responsible, :presence => {:message => "Campo obrigatório"}
    validates :active, :inclusion => {:in => [true, false]}
    validates :hours, :presence => {:message => "Campo obrigatório"}
    validates :phone1, :presence => {:message => "Campo obrigatório"}

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

    before_action :set_customer, only: [:edit, :update, :destroy]
    load_and_authorize_resource

    def index
        @customers = Admin::Customer.select('id, name, responsible, active, hours, phone1, phone2, address').all
    end

    def new
        @customer = Admin::Customer.new
    end

    def edit
    end

    def create
        @customer = Admin::Customer.new(customer_params)
        respond_with @customer, location: @customer.save ? admin_customers_path : new_admin_customer_path(@customer)
    end

    def update
        respond_with @customer, location: @customer.update(customer_params) ? admin_customers_path : edit_admin_customer_path(@customer)
    end

    def destroy
        respond_with @customer, location: admin_customers_path if @customer.destroy
    end

    private

    def set_customer
        @customer = Admin::Customer.find(params[:id])
    end

    def customer_params
        params.require(:admin_customer).permit(:name, :responsible, :active, :hours, :phone1, :phone2, :address)
    end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_form.html.erb
<% content_for :style do -%>
    <%= stylesheet_link_tag "admin/select2" %> <!-- dropdown -->
  <%= stylesheet_link_tag 'admin/jquery-ui-1.10.4.custom' %>
<% end -%>

<% content_for :script do -%>
    <%= javascript_include_tag "admin/select2" %> <!-- dropdown -->
    <%= javascript_include_tag "admin/select2_locale_pt-BR" %> <!-- dropdown -->
	<%= javascript_include_tag 'jquery.validate.min' %> <!-- validação formulário -->
	<%= javascript_include_tag 'admin/jquery.maskedinput' %> <!-- máscara campos -->

    <script>
        $('input[name="admin_customer[phone1]"]').mask("(99)9999-9999?9");
        $('input[name="admin_customer[phone2]"]').mask("(99)9999-9999?9");

        //Validação do formulário
        $("form.formValidate").validate({
            rules: {
                'admin_customer[name]':
                {
                    required: true
                },
                'admin_customer[responsible]':
                {
                    required: true
                },
                'admin_customer[hours]':
                {
                    required: true,
                    number: true
                },
                'admin_customer[phone1]':
                {
                    required: true
                }
            },
            messages: {
                'admin_customer[name]': {
                    required: "O nome é obrigatório."
                },
                'admin_customer[responsible]': {
                    required: "O nome do responsável é obrigatório."
                },
                'admin_customer[hours]': {
                    required: "As horas contratadas é obrigatório.",
                    number: "Insira um número"
                },
                'admin_customer[phone1]': {
                    required: "O telefone é obrigatório."
                }
            }
        });
    </script>

<% end -%>

<div class="panel-body">
  <% if flash[:alert] %>
      <div class="alert alert-warning fade in fadeOut">
        <button class="close close-sm" type="button" data-dismiss="alert">
          <i class="fa fa-times"></i>
        </button>
        <%= flash[:alert] %>
      </div>
  <% end %>

    <%= simple_form_for(@customer, html: {class: "form-horizontal formValidate"}) do |f| %>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Nome
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :name, :required => true, :autofocus => true, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Responsável
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :responsible, :required => true, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Ativo?
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.check_box :active, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Horas Contratadas
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :hours, :required => true, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Telefone 1
              <span class="text-danger">*</span>
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :phone1, :required => true, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Telefone 2
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :phone2, :class => "form-control" %>
	  		</div>
	  	</div>

	  	<div class="form-group">
	  		<label class="control-label col-lg-2">Endereço
	  		</label>
	  		<div class="col-lg-4 iconic-input right">
	  			<%= f.text_field :address, :class => "form-control" %>
	  		</div>
	  	</div>

		<%= link_to 'Voltar', {:action => "index"}, :class => 'btn btn-shadow btn-default' %>
		<div class="pull-right">
			<%= f.submit "Salvar", class: "btn btn-shadow btn-primary" %>
		</div>
	<% end %>

</div>

 <span class="loader">
 <%= image_tag "admin/loading.gif", :width => "80px" %>
</span>
<div style="position:fixed;" class="maskLoader"></div>

app/views/admin/customers/_grid.html.erb
<%# <td class="center hidden-phone">5</td> - classe para centralizar e esconder qdo responsivo %>

<table  class="display table table-bordered table-striped" id="data_table">
    <thead>
    <tr>
        <th>Nome</th>
        <th class="hidden-phone">Responsável</th>
        <th class="hidden-phone">Ativo?</th>
        <th class="hidden-phone">Horas Contrat.</th>
        <% if can? :update, Admin::Customer %>
            <th>Editar</th>
        <% end %>
        <% if can? :destroy, Admin::Customer %>
            <th>Excluir</th>
        <% end %>
    </tr>
    </thead>
    <tbody>

    <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.name %></td>
            <td class="hidden-phone"><%= customer.responsible %></td>
            <td class="hidden-phone"><%= customer.active? ? "Sim" : "Não" %></td>
            <td class="hidden-phone"><%= customer.hours %></td>
            <% if can? :update, Admin::Customer %>
                <td class="center">
                    <%= link_to(edit_admin_customer_path(customer), :class => 'btn btn-primary btn-xs') do %>
                        <i class="fa fa-pencil fa-lg"></i>
                    <% end %>
                </td>
            <% end %>
            <% if can? :destroy, Admin::Customer %>
                <td class="center">
                    <%= link_to(admin_customer_path(customer), :class => 'btn btn-danger btn-xs btn-excluir-grid', :id => customer.id) do %>
                        <i class="fa fa-trash-o fa-lg"></i>
                    <% end %>
                </td>
            <% end %>
        </tr>
    <% end %>

    </tbody>

</table>

<span class="loader" style="left:50%;">
    <%= image_tag "admin/loading.gif", :width => "80px" %>
</span>
<div style="position:fixed;" class="maskLoader"></div>

<script type="text/javascript">
    $(function (){
        //datatable
        $('#data_table').dataTable( {
            "aaSorting": [[ 0, "asc" ]],
            "oLanguage": {
                "sUrl": "/datatable_pt.txt"
            },
            "aoColumnDefs": [
                { "bSortable": true, "aTargets": [ 0 ] },
                { "bSearchable": false, "aTargets": [ 2, 3 ] }
            ]
        } );
    });
</script>

app/views/admin/customers/edit.html.erb
<section class="panel">
	<header class="panel-heading">
		Edição de Cliente
	</header>

	<div id="renderForm">
		<%= render 'form' %>
	</div>
</section>

app/views/admin/customers/index.html.erb
<% content_for :style do -%>
    <%= stylesheet_link_tag "admin/demo_page" %> <!-- datatable -->
    <%= stylesheet_link_tag "admin/demo_table" %> <!-- datatable -->
    <%= stylesheet_link_tag "admin/DT_bootstrap" %> <!-- datatable -->
<% end -%>

<% content_for :script do -%>
    <%= javascript_include_tag 'admin/jquery.dataTables' %> <!-- datatable -->
    <%= javascript_include_tag "admin/DT_bootstrap" %> <!-- datatable -->

    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {

            $(document).on('click','a.btn-excluir-grid',function () {
                if(confirm("Você tem certeza que deseja excluir?"))
                {
                    $('span.loader').show();
                    $('div.maskLoader').show();
                    var linha = $(this).closest('tr');
                    id = $(this).attr('id');
                    $.ajax({
                        url: '/admin/customers/delete/'+id,
                        type: 'POST',
                        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                        // data: {id: id},
                    })
                    .done(function() {
                        // $(linha).remove();
                        $.get(this.href, $(this).serialize(), null, 'script');
                    })
                    .fail(function() {
                        console.log("erro ao excluir");
                        $('span.loader').hide();
                        $('div.maskLoader').hide();
                    });
                    $.ajaxSetup({
                      headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                      }
                    });
                }
                return false;
            });

        } );
    </script>

<% end -%>

<section class="panel">
    <header class="panel-heading">
        Lista de Clientes
    </header>

  <% if flash[:notice] %>
      <div class="alert alert-success fade in fadeOut">
        <button class="close close-sm" type="button" data-dismiss="alert">
          <i class="fa fa-times"></i>
        </button>
        <%= flash[:notice] %>
      </div>
  <% end %>

    <div class="panel-body">
        <div class="btn-group">
            <% if can? :create, Admin::Customer %>
                <%= link_to(new_admin_customer_path, :class => 'btn btn-shadow btn-primary', :style => 'margin-bottom:10px;') do %>
                    Adicionar <i class="fa fa-plus"></i>
                <% end %>
            <% end %>
        </div>
        <div class="adv-table">
            <%= render 'grid' %>
        </div>
    </div>
</section>

app/views/admin/customers/new.html.erb
<section class="panel">
	<header class="panel-heading">
		Cadastro de Cliente
	</header>

	<div id="renderForm">
		<%= render 'form' %>
	</div>
</section>